// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRMe3QZBhuCUkNv679ziyQ7x0Egll_e3M',
    appId: '1:405557219138:web:48f3560901e7ecd5d902db',
    messagingSenderId: '405557219138',
    projectId: 'sakanayoi-ikan',
    authDomain: 'sakanayoi-ikan.firebaseapp.com',
    databaseURL: 'https://sakanayoi-ikan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sakanayoi-ikan.appspot.com',
    measurementId: 'G-SMHWTJCREB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLHKpCSczN2ot5DUKhdK7cUT3YiT9dfY',
    appId: '1:405557219138:android:e149bd95a9349b57d902db',
    messagingSenderId: '405557219138',
    projectId: 'sakanayoi-ikan',
    databaseURL: 'https://sakanayoi-ikan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sakanayoi-ikan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHynpw60-DmiVS0LB3PkjYp6TRVIK-86g',
    appId: '1:405557219138:ios:8073efbd6e60b26fd902db',
    messagingSenderId: '405557219138',
    projectId: 'sakanayoi-ikan',
    databaseURL: 'https://sakanayoi-ikan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sakanayoi-ikan.appspot.com',
    iosClientId: '405557219138-hmuhq6saajmom4888gtig8pt4jdva9vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakanaYoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHynpw60-DmiVS0LB3PkjYp6TRVIK-86g',
    appId: '1:405557219138:ios:8073efbd6e60b26fd902db',
    messagingSenderId: '405557219138',
    projectId: 'sakanayoi-ikan',
    databaseURL: 'https://sakanayoi-ikan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sakanayoi-ikan.appspot.com',
    iosClientId: '405557219138-hmuhq6saajmom4888gtig8pt4jdva9vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakanaYoi',
  );
}
